import { Meetup, WorkoutRecord } from '@/types';

export const DUMMY_MEETUPS: Array<Meetup & { participants: { id: string; nickname: string; isHost?: boolean }[] }> = [
  {
    id: '1',
    hostId: 'user-2',
    host: {
      id: 'user-2',
      nickname: '박운동',
      exerciseLevel: 4,
      trustScore: 87,
      trustGrade: 'excellent',
      joinCount: 24,
      certCount: 20,
      noshowCount: 0,
      createdAt: '',
    },
    title: '한강 저녁 러닝 같이해요 🏃',
    sportType: 'running',
    location: { address: '서울 성동구 성수동 한강변', district: '성수동', lat: 37.5172, lng: 127.0286 },
    scheduledAt: new Date(Date.now() + 2 * 3600000).toISOString(),
    maxParticipants: 5,
    currentParticipants: 3,
    minLevel: 2,
    maxLevel: 4,
    minTrustScore: 0,
    description: '퇴근 후 가볍게 5km 같이 뛰어요! 페이스는 5:30~6:00/km 정도로 맞출 예정이에요. 초보도 환영합니다 :)',
    distanceMeters: 300,
    createdAt: '',
    participants: [
      { id: 'user-2', nickname: '박운동', isHost: true },
      { id: 'user-3', nickname: '김*준' },
      { id: 'user-4', nickname: '이*현' },
    ],
  },
  {
    id: '2',
    hostId: 'user-3',
    host: {
      id: 'user-3',
      nickname: '헬스왕',
      exerciseLevel: 3,
      trustScore: 62,
      trustGrade: 'manner',
      joinCount: 12,
      certCount: 10,
      noshowCount: 1,
      createdAt: '',
    },
    title: '강남 헬스 같이하실 분 💪',
    sportType: 'gym',
    location: { address: '서울 강남구 역삼동 스포애니 역삼점', district: '역삼동', lat: 37.501, lng: 127.036 },
    scheduledAt: new Date(Date.now() + 3 * 3600000).toISOString(),
    maxParticipants: 4,
    currentParticipants: 2,
    minLevel: 1,
    maxLevel: 5,
    minTrustScore: 0,
    description: '오늘 등/어깨 운동 할 예정이에요. 같이 하실 분 환영! 서로 피드백 주면서 열심히 해봐요.',
    distanceMeters: 1200,
    createdAt: '',
    participants: [
      { id: 'user-3', nickname: '헬스왕', isHost: true },
      { id: 'user-5', nickname: '최*호' },
    ],
  },
  {
    id: '3',
    hostId: 'user-4',
    host: {
      id: 'user-4',
      nickname: '클라이머K',
      exerciseLevel: 3,
      trustScore: 45,
      trustGrade: 'normal',
      joinCount: 8,
      certCount: 7,
      noshowCount: 0,
      createdAt: '',
    },
    title: '클라이밍 초보 환영! 🧗',
    sportType: 'climbing',
    location: { address: '서울 마포구 합정동 더클라임 합정점', district: '합정동', lat: 37.549, lng: 126.914 },
    scheduledAt: new Date(Date.now() + 5 * 3600000).toISOString(),
    maxParticipants: 6,
    currentParticipants: 4,
    minLevel: 1,
    maxLevel: 3,
    minTrustScore: 30,
    description: '초보자도 편하게 오세요! 기본 동작부터 같이 배워가는 모임이에요. 암벽화는 현장 대여 가능합니다.',
    distanceMeters: 2100,
    createdAt: '',
    participants: [
      { id: 'user-4', nickname: '클라이머K', isHost: true },
      { id: 'user-6', nickname: '정*연' },
      { id: 'user-7', nickname: '한*민' },
      { id: 'user-8', nickname: '오*진' },
    ],
  },
  {
    id: '4',
    hostId: 'user-5',
    host: {
      id: 'user-5',
      nickname: '자전거신',
      exerciseLevel: 5,
      trustScore: 95,
      trustGrade: 'champion',
      joinCount: 41,
      certCount: 38,
      noshowCount: 0,
      createdAt: '',
    },
    title: '한강 자전거 라이딩 🚴',
    sportType: 'cycling',
    location: { address: '서울 영등포구 여의도동 한강공원 자전거도로', district: '여의도', lat: 37.528, lng: 126.933 },
    scheduledAt: new Date(Date.now() + 24 * 3600000).toISOString(),
    maxParticipants: 10,
    currentParticipants: 6,
    minLevel: 2,
    maxLevel: 5,
    minTrustScore: 30,
    description: '여의도~잠실 왕복 40km 라이딩! 평균 속도 25km/h 이상 유지 가능한 분. 자전거 정비 필수입니다.',
    distanceMeters: 3400,
    createdAt: '',
    participants: [
      { id: 'user-5', nickname: '자전거신', isHost: true },
      { id: 'user-9', nickname: '강*우' },
      { id: 'user-10', nickname: '윤*서' },
      { id: 'user-11', nickname: '임*혁' },
      { id: 'user-12', nickname: '배*은' },
      { id: 'user-13', nickname: '신*호' },
    ],
  },
  {
    id: '5',
    hostId: 'user-6',
    host: {
      id: 'user-6',
      nickname: '수영장인',
      exerciseLevel: 4,
      trustScore: 73,
      trustGrade: 'manner',
      joinCount: 18,
      certCount: 16,
      noshowCount: 1,
      createdAt: '',
    },
    title: '새벽 수영 함께해요 🏊',
    sportType: 'swimming',
    location: { address: '서울 송파구 잠실동 잠실실내수영장', district: '잠실동', lat: 37.514, lng: 127.101 },
    scheduledAt: new Date(Date.now() + 14 * 3600000).toISOString(),
    maxParticipants: 4,
    currentParticipants: 1,
    minLevel: 2,
    maxLevel: 5,
    minTrustScore: 0,
    description: '매일 새벽 6시 수영장 오픈 런! 1시간 동안 1km 이상 목표로 꾸준히 같이 해요. 실력 무관 환영.',
    distanceMeters: 5200,
    createdAt: '',
    participants: [
      { id: 'user-6', nickname: '수영장인', isHost: true },
    ],
  },
];

export const DUMMY_WORKOUT_RECORDS: WorkoutRecord[] = [
  {
    id: 'r1',
    userId: 'guest',
    meetupId: '1',
    meetupTitle: '한강 저녁 러닝',
    sportType: 'running',
    startedAt: new Date(Date.now() - 3600000).toISOString(),
    endedAt: new Date().toISOString(),
    durationSeconds: 2120,
    distanceMeters: 5200,
    calories: 312,
    avgHeartRate: 142,
    comment: '오늘도 완료! 🔥',
    location: { address: '서울 성동구 성수동', district: '성수동', lat: 37.544, lng: 127.057 },
  },
  {
    id: 'r2',
    userId: 'guest',
    sportType: 'gym',
    startedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    endedAt: new Date(Date.now() - 2 * 86400000 + 4800000).toISOString(),
    durationSeconds: 4800,
    calories: 280,
    comment: '하체 완전 박살 💀',
    location: { address: '서울 강남구 역삼동', district: '역삼동', lat: 37.501, lng: 127.036 },
  },
  {
    id: 'r3',
    userId: 'guest',
    sportType: 'climbing',
    startedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    endedAt: new Date(Date.now() - 4 * 86400000 + 5400000).toISOString(),
    durationSeconds: 5400,
    calories: 350,
    location: { address: '서울 마포구 합정동', district: '합정동', lat: 37.549, lng: 126.914 },
  },
];
